name: Test Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Use bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies ⏬
      run: bun install

    - name: Lint code 💄
      run: bun run lint

    - name: Typecheck code 🤖
      run: bun run typecheck

    - name: Test code ✅
      run: bun test --coverage --coverage-reporter=lcov

    - name: Build artifacts 🏗️
      run: bun run build

    - name: Publish to coveralls ⭐
      # coverage/lcov.info was generated in the previous npm run build step
      uses: coverallsapp/github-action@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
